#!/bin/bash

# If the user forgets to specify the name of the folder
if [ -z "$1" ]; then
    echo "Error: you need to specify the name of the folder you want to encrypt."
    echo "Example: encrypt.sh <folder_name>"
    exit 1
fi

# Autogenerated key 
SECURE_KEY=$(openssl rand -base64 32)
echo "In case you need a new key you can use this: $SECURE_KEY"
echo "$SECURE_KEY" >> keys

FOLDER="$1"
ARCHIVE="$FOLDER.tar.zst"
ENCRYPTED_ARCHIVE="$ARCHIVE.enc"

tar --use-compress-program="zstd" \
	-cvf \
	"$ARCHIVE" \
	"$FOLDER"

openssl enc \
	-aes-256-cbc \
	-salt \
	-pbkdf2 \
	-in "$ARCHIVE" \
	-out "$ENCRYPTED_ARCHIVE"

rm -f "$ARCHIVE"